### ISSUE TITLE
[Request] Switch - Customizable Save/Config Path

### ISSUE THREAD

**Issue by 16BitWonder** [fgsfdsfgs/sm64pc#10]
Without a way to launch the application with --savepath specified, would it be at all possible that an option is added to specify where the save/config is being saved rather than defaulting to the root of the SD card?

**Comment by fgsfdsfgs** [comment]
It shouldn't actually default to the root of the SD card unless you're like using a forwarder or something. It should be in the same directory as the NRO. Other than that, how would you specify the directory? You would need to read it from a file somewhere, which means at least something must be by the NRO or in the root of the SD card.

**Comment by fgsfdsfgs** [comment]
The SD card root thing should be fixed as of 4876508. It will now properly store saves/configs in the working directory (usually the same as where the NRO is).

**Comment by 16BitWonder** [comment]
Awesome, thank you for looking into it!
I preferred the old system of it saving in the NRO directory and was thrown off when it was writing to the root of the SD.

**Comment by fgsfdsfgs** [comment]
Yeah it wasn't supposed to be doing that. I could have sworn that the SDL path functions return `"."` on the Switch, but apparently they just return `NULL`, and on the Switch relative paths map to the root of the SD card by default.
