### ISSUE TITLE
"The software was closed because an error occured."

### ISSUE THREAD

**Issue by coatlessali** [fgsfdsfgs/sm64pc#11]
The compiled .nro file does not function. Used `make BETTERCAMERA=1 NODRAWINGDISTANCE=1 TEXTURE_FIX=1 EXTERNAL_DATA=1 -j12` as makeflags.

Steps to reproduce:
Compile on Arch Linux.
Move compiled .nro file to `sdmc:/switch/`.
Attempt to launch.

**Expected behavior**
Game reaches title screen.

**Comment by impeeza** [comment]
If you use externaldata compiler switch YOU MUST TO EXTRACT the zip file with resources on res folder of sd root. If you fail to do that, the error you mention is expected

**Comment by coatlessali** [comment]
Where can I find this zip file?

**Comment by coatlessali** [comment]
The zip file has been found.
