### ISSUE TITLE
The command "source $DEVKITPRO/switchvars.sh" does not work

### ISSUE THREAD

**Issue by Gaelcraft** [fgsfdsfgs/sm64pc#13]
The command "source $DEVKITPRO/switchvars.sh" does not work I get "No such file or directory" and I already tried to put "export DEVKITPRO=/opt/devkitpro" and if I installed everything correctly and I can even compile the pc port

I'm on windows 10

**Comment by impeeza** [comment]
The packages bar changed and now you need to follow the devkitpro installation page in order to install them new ones

**Comment by Gaelcraft** [comment]
I already did it as in the page and it still does not work

**Comment by Gaelcraft** [comment]
When I compile the game it gets here "aarch64-none-elf-gcc.exe: error: unrecognized command-line option '-mwindows'
make: *** [Makefile: 1036: build / us_nx / sm64.us.f3dex2e] Error 1 "

**Comment by impeeza** [comment]
I did have to change my compilation manual to accommodate to new packages. I am just now at hospital when I go back to home will publish the new version on gbatemp thread

**Comment by Gaelcraft** [comment]
Ok

**Comment by nat522** [comment]
Im having this so what is the way to do this

**Comment by impeeza** [comment]
SwitchVars.sh was installed by a old package, today you need the next packages:

switch-dev devkitA64 dkp-toolchain-vars libnx switch-tools switch-mesa switch-libdrm_nouveau switch-sdl2

they setup all your environment.
