### ISSUE TITLE
Compiler errors msys2 mingw

### ISSUE THREAD

**Issue by nex86** [fgsfdsfgs/sm64pc#16]
getting these errors when compiling in msys2 mingw

already set up devkitpro environment 

`make: Entering directory '/home/nexxu/sm64ex/tools'
gcc -Llib -Iinclude -I../include -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  n64graphics_ci_dir/n64graphics_ci.c n64graphics_ci_dir/exoquant/exoquant.c n64graphics_ci_dir/utils.c -lm -o n64graphics_ci -O2
gcc -Llib -Iinclude -I../include -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  n64cksum.c libmio0.c libsm64.c utils.c -lm -o n64cksum
In file included from n64cksum.c:5:
utils.h:74: warning: "ERROR" redefined
   74 | #define ERROR(...) fprintf(stderr, __VA_ARGS__)
      |
In file included from C:/msys64/mingw64/include/windows.h:71,
                 from utils.h:10,
                 from n64cksum.c:5:
C:/msys64/mingw64/include/wingdi.h:75: note: this is the location of the previous definition
   75 | #define ERROR 0
      |
In file included from libmio0.c:10:
utils.h:74: warning: "ERROR" redefined
   74 | #define ERROR(...) fprintf(stderr, __VA_ARGS__)
      |
In file included from C:/msys64/mingw64/include/windows.h:71,
                 from utils.h:10,
                 from libmio0.c:10:
C:/msys64/mingw64/include/wingdi.h:75: note: this is the location of the previous definition
   75 | #define ERROR 0
      |
In file included from libsm64.c:7:
utils.h:74: warning: "ERROR" redefined
   74 | #define ERROR(...) fprintf(stderr, __VA_ARGS__)
      |
In file included from C:/msys64/mingw64/include/windows.h:71,
                 from utils.h:10,
                 from libsm64.c:7:
C:/msys64/mingw64/include/wingdi.h:75: note: this is the location of the previous definition
   75 | #define ERROR 0
      |
In file included from utils.c:16:
utils.h:74: warning: "ERROR" redefined
   74 | #define ERROR(...) fprintf(stderr, __VA_ARGS__)
      |
In file included from C:/msys64/mingw64/include/windows.h:71,
                 from utils.h:10,
                 from utils.c:16:
C:/msys64/mingw64/include/wingdi.h:75: note: this is the location of the previous definition
   75 | #define ERROR 0
      |
gcc -Llib -Iinclude -I../include -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  textconv.c utf8.c hashtable.c -lm -o textconv
gcc -Llib -Iinclude -I../include -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  patch_libultra_math.c -lm -o patch_libultra_math
patch_libultra_math.c: In function 'main':
patch_libultra_math.c:113:26: warning: overflow in conversion from 'long long unsigned int' to 'long int' changes value from '18446744073709551564' to '-52' [-Woverflow]
  113 |                 fseek(f, -sizeof(hdr), SEEK_CUR);
      |                          ^~~~~~~~~~~~
gcc -Llib -Iinclude -I../include -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  iplfontutil.c -lm -o iplfontutil -O2
gcc -Llib -Iinclude -I../include -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  aiff_extract_codebook.c -lm -o aiff_extract_codebook
gcc -Llib -Iinclude -I../include -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  sdk-tools/adpcm/vadpcm_enc.c sdk-tools/adpcm/vpredictor.c sdk-tools/adpcm/quant.c sdk-tools/adpcm/util.c sdk-tools/adpcm/vencode.c -lm -o vadpcm_enc -Wno-unused-result -Wno-uninitialized -Wno-sign-compare -Wno-absolute-value
gcc -Llib -Iinclude -I../include -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  sdk-tools/tabledesign/codebook.c sdk-tools/tabledesign/estimate.c sdk-tools/tabledesign/print.c sdk-tools/tabledesign/tabledesign.c -lm -o tabledesign -Wno-uninitialized -laudiofile -lstdc++
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -laudiofile: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:54: tabledesign] Error 1
make: Leaving directory '/home/nexxu/sm64ex/tools'
Makefile:212: *** Failed to build tools.  Stop.

`

**Comment by impeeza** [comment]
This space is for issue reports, but compiling could be one because the instructions on readme are outdated.

Follow the guide on:

https://gbatemp.net/threads/mario-64-port.564633/page-17#post-9149081

Check the prerequisites and packages needed

**Comment by nex86** [comment]
yea that wasn't the issue but I fixed it, I downloaded the wrong branch..
