### ISSUE TITLE
Game freezes on Course 3 when Mario dive on the water

### ISSUE THREAD

**Issue by leandrodeassis** [fgsfdsfgs/sm64pc#7]
When I use NODRAWINGDISTANCE=1 the game freezes on Course 3 when Mario dive on the water. Someone managed to solve this problem?

EDIT: It's the Switch version

**Comment by leandrodeassis** [comment]
oh now i see https://github.com/sm64pc/sm64pc/issues/173
the switch branch doesn't have the nightly push, right?

**Comment by leandrodeassis** [comment]
for information: using the https://github.com/sm64pc/sm64pc/blob/nightly/src/game/bettercamera.inc.h solved the problem.

**Comment by fgsfdsfgs** [comment]
This should now be fixed in the `switch` branch.
